local bufnr = vim.api.nvim_get_current_buf()

vim.keymap.set('n', '<leader>a', function()
    vim.cmd.RustLsp('codeAction')
end, { desc = 'codeAction', silent = true, buffer = bufnr })
vim.keymap.set('n', 'K', function()
    vim.cmd.RustLsp({ 'hover', 'actions' })
end, { desc = 'hoverAction', silent = true, buffer = bufnr })
vim.keymap.set('n', '<leader>m', function()
    vim.cmd.RustLsp({ 'expandMacro' })
end, { desc = 'expandMacro', silent = true, buffer = bufnr })
